import { expect, test } from '@playwright/test'

test.describe('Repwise core offline workflow', () => {
  test('browses the complete local exercise catalog', async ({ page }) => {
    await page.goto('./#/exercises')
    await expect(page.getByText('876 of 876 exercises')).toBeVisible({ timeout: 30_000 })
    await page.getByLabel('Search').fill('Barbell Bench Press - Medium Grip')
    await expect(page.getByText('1 of 876 exercises')).toBeVisible()
    await page.getByRole('button', { name: /Barbell Bench Press - Medium Grip/ }).click()
    await expect(page.getByRole('dialog', { name: 'Barbell Bench Press - Medium Grip' })).toBeVisible()
    const demonstration = page.getByRole('dialog', { name: 'Barbell Bench Press - Medium Grip' }).getByRole('img')
    await expect(demonstration).toHaveAttribute('src', /\/Repwise\/catalog\/media\/barbell-bench-press-medium-grip\/start\.webp$/)
    await expect.poll(() => demonstration.evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
    await expect(page.getByRole('heading', { name: 'Instructions' })).toBeVisible()
  })

  test('persists an interrupted workout, set facts, and rest timer', async ({ page }) => {
    await page.goto('./#/today')
    await expect(page.getByText(/Catalog:.*up to date/)).toBeVisible({ timeout: 30_000 })
    await page.getByLabel('Workout name').fill('Offline Push')
    await page.getByRole('button', { name: 'Start workout' }).click()
    await expect(page).toHaveURL(/#\/workout$/)
    await expect(page.getByRole('heading', { name: 'Workout', exact: true })).toBeVisible()
    await expect(page.getByText('Repwise is ready offline')).toBeVisible({ timeout: 30_000 })
    await page.getByRole('button', { name: '+ Add exercise' }).click()
    await page.getByLabel('Search exercises').fill('Barbell Bench Press - Medium Grip')
    await page.getByRole('button', { name: /Barbell Bench Press - Medium Grip/ }).click()
    await page.getByRole('button', { name: '+ Add Set' }).click()
    await page.getByRole('button', { name: /View Barbell Bench Press - Medium Grip demonstration/ }).click()
    await expect(page.getByRole('dialog', { name: 'Barbell Bench Press - Medium Grip' })).toBeVisible()
    await page.getByRole('button', { name: 'Close demonstration' }).click()
    await page.getByLabel('Load (kg)').fill('70')
    await page.getByLabel('Reps').fill('8')
    await page.getByRole('button', { name: 'Mark complete' }).click()
    await expect(page.getByRole('group', { name: 'Rest timer' })).toBeVisible()

    await page.reload()
    await expect(page.getByLabel('Workout name')).toHaveValue('Offline Push')
    await expect(page.getByLabel('Load (kg)')).toHaveValue('70')
    await expect(page.getByLabel('Reps')).toHaveValue('8')
    await expect(page.getByRole('button', { name: 'Completed' })).toBeVisible()
    await expect(page.getByRole('group', { name: 'Rest timer' })).toBeVisible()
    await page.getByRole('button', { name: 'Finish workout' }).click()
    await expect(page).toHaveURL(/#\/today$/)
    await expect(page.getByText('Offline Push')).toBeVisible()
  })

  test('starts the selected built-in rotation day as an editable active workout', async ({ page }) => {
    await page.goto('./#/today')
    await expect(page.getByText(/Catalog:.*up to date/)).toBeVisible({ timeout: 30_000 })
    const program = page.getByRole('region', { name: 'My Program' })
    const dayA = program.locator('article').filter({ hasText: 'Day A' })
    await dayA.getByRole('button', { name: 'Start' }).click()

    await expect(page).toHaveURL(/#\/workout$/)
    await expect(page.getByText('Incline Chest Press Machine', { exact: true })).toBeVisible()
    await expect(page.getByLabel('Reps')).toHaveCount(20)
    await expect(page.getByLabel('Reps').first()).toHaveValue('8')
    await expect(page.getByLabel('Load (kg)').first()).toHaveValue('')
    await page.getByRole('button', { name: 'Discard' }).click()
    await page.getByRole('button', { name: 'Discard' }).last().click()
    await expect(page).toHaveURL(/#\/today$/)
  })

  test('generates a deterministic workout and remains usable offline', async ({ page, context, browserName }) => {
    test.skip(browserName === 'webkit', 'Playwright WebKit does not expose reliable offline emulation on Windows.')
    await page.goto('./#/today')
    await expect(page.getByText(/Catalog:.*up to date/)).toBeVisible({ timeout: 30_000 })
    await page.getByRole('button', { name: 'Generate' }).click()
    await expect(page.getByRole('button', { name: 'Start this workout' })).toBeVisible()
    await expect(page.locator('section').filter({ hasText: 'Build a workout' }).locator('ol > li').first()).toBeVisible()

    await page.evaluate(async () => { await navigator.serviceWorker.ready })
    await page.reload()
    await page.waitForFunction(() => navigator.serviceWorker?.controller !== null, undefined, { timeout: 60_000 })
    await context.setOffline(true)
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Today' })).toBeVisible()
    await page.getByRole('link', { name: 'Exercises' }).click()
    await expect(page.getByText('876 of 876 exercises')).toBeVisible({ timeout: 30_000 })
    await expect(page.getByText(/offline — using local data/)).toHaveCount(0)
  })

  test('changes the interface language in Settings, keeps it across navigation and reload, then restores English', async ({ page }) => {
    await page.goto('./#/settings')
    await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible({ timeout: 30_000 })

    await page.getByRole('button', { name: 'Français' }).click()
    await expect(page.getByRole('heading', { name: 'Réglages' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Français' })).toHaveAttribute('aria-pressed', 'true')

    await page.getByRole('link', { name: 'Aujourd’hui' }).click()
    await expect(page).toHaveURL(/#\/today$/)
    await expect(page.getByRole('heading', { name: 'Aujourd’hui' })).toBeVisible()

    await page.reload()
    await expect(page.getByRole('heading', { name: 'Aujourd’hui' })).toBeVisible({ timeout: 30_000 })
    await expect(page.evaluate(() => document.documentElement.lang)).resolves.toBe('fr')

    await page.getByRole('link', { name: 'Réglages' }).click()
    await page.getByRole('button', { name: 'English' }).click()
    await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'English' })).toHaveAttribute('aria-pressed', 'true')
  })
})
